# Generated by Django 3.1 on 2023-01-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('point', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use_point', models.BooleanField(blank=True, default=False, null=True)),
                ('is_use_cash', models.BooleanField(blank=True, default=False, null=True)),
                ('use_point', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('use_cash', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('add_point', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.member')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.author'),
        ),
    ]
